service: aws-lambda-crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:717432281447:table/Games

functions:
  hello:
    handler: hello.hello
    events:
      - httpApi:
          path: /
          method: get
  addGames:
    handler: src/addGames.addGames
    events:
      - httpApi:
          path: /games
          method: post
   getGames:
    handler: src/getGames.getGames
    events:
      - httpApi:
          path: /games
  getGame:
    handler: src/getGame.getGame
    events:
      - httpApi:
          path: /games/{id}
          method: get
  updateGames:
    handler: src/updateGames.updateGames
    events:
      - httpApi:
          path: /games/{id}
          method: put

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Games
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH